exclude: "venv|vendor|build"
default_stages: [pre-commit]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
            exclude: ".vscode(.dist)?/.*"
          - id: check-yaml
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-shebang-scripts-are-executable
          - id: mixed-line-ending
          - id: detect-private-key

    - repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: python -m mypy
            language: system
            types: [python]
            require_serial: true
          - id: ruff-check
            name: ruff
            entry: ruff check --force-exclude --fix
            language: system
            types: [python]
            require_serial: true
          - id: ruff-format
            name: ruff
            entry: ruff format --force-exclude
            language: system
            types: [python]
            require_serial: true
          - id: dprint
            name: dprint
            entry: dprint fmt --allow-no-files
            language: system
            require_serial: true

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
